apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: manual-sole-nodejs 
  janus-idp.io/tekton: manual-sole-nodejs
  backstage.io/kubernetes-id: manual-sole-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: manual-sole-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  